### ISSUE TITLE
Phantom JS errors out on aureliaPal.PLATFORM.performance.now

### ISSUE THREAD

**Issue by davidbfrogman** [aurelia/pal#6]
Error Message:
phantom stdout: TypeError: 'undefined' is not an object (evaluating '_aureliaPal.PLATFORM.performance.now')

I'm trying to run prerender.io locally.  Which I have for the most part figured out, and is almost working.  Prerender.io spins up phantom.js instances to render the page.  It actually gets pretty far, but then it always manages to fail here.  In other situations like this, I just created polyfills for phantom.js.  However I really can't even see what tricky thing aureliaPal is trying to do to create a polyfill for it.

You can see my other polyfills here:
https://github.com/davidbfrogman/DBPAurelia/blob/master/src/3rdParty/phantompolyfill.js

For instance when I saw other errors in phantom.js it turned out that it didn't have a implementation for window.requestAnimationFrame.  Found a polyfill, and fixed it.

I wish I could put together a better defect description than this.  I hope this makes sense.

**Comment by EisenbergEffect** [comment]
@jdanyow Can you check on this?

**Comment by davidbfrogman** [comment]
Thinking about this more.  Running Prerender locally is actually pretty simple.  That might be the easiest way to look at, and reproduce this error locally.

https://github.com/prerender/prerender

I haven't tried running it on a blank skeleton app, but I'd be curious to know if there's just something interesting about my application that's different.

**Comment by davidbfrogman** [comment]
Is there any progress here?

**Comment by jdanyow** [comment]
hi @davidbfrogman- you'll need to polyfill performance.now in browsers that don't have it.

Google bot and others probably aren't doing a good job speed testing their site because at the moment the document loads or is "ready" there are still things going on in the micro-task-queue (promise chains, etc).  Do any of these tools offer some sort of "hook" where you can tell them that the app is rendered? If so, a good place to do that would be in the `attached` callback of your app.js

**Comment by davidbfrogman** [comment]
Yeah I'll try and do that.

You can see my other struggles and victories in this: https://github.com/aurelia/framework/issues/310

I'll let you know how that works out in a few days when I can get back to this.
